#define FLOW_TAP_TERM 120
#define CHORDAL_HOLD
#define PERMISSIVE_HOLD

#define USB_SUSPEND_WAKEUP_DELAY 0
#undef MOUSEKEY_WHEEL_DELAY
#define MOUSEKEY_WHEEL_DELAY 50

#define SERIAL_NUMBER "ZGlne/qmlP0Z"
#define LAYER_STATE_8BIT
#define COMBO_COUNT 7

#define TAPPING_TERM_PER_KEY
#define NAVIGATOR_SCROLL_DIVIDER 50

#define NAVIGATOR_TRACKBALL_ROTATION 335
#define NAVIGATOR_AIM_LAYERS {2}
#define NAVIGATOR_SCROLL_INVERT_X
#define NAVIGATOR_SCROLL_INVERT_Y
#define RGB_MATRIX_STARTUP_SPD 60

